services:
  postgres:
    image: postgres
    container_name: nest_postgres
    env_file:
     - ../../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/postgresql/data

volumes:
  postgres_data:



#------------------------

#services:
  #postgres:
    #image: postgres
    #container_name: nest_postgres
    #env_file:
    # - ../../.env
    #environment:
    #  - POSTGRES_USER=${POSTGRES_USER}
    #  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # - POSTGRES_DB=${POSTGRES_DB}
    #ports:
    #  - '5432:5432'
    #volumes:
    #  - postgres_data:/data

#volumes:
  #postgres_data:
