apiVersion: apps/v1
kind: Deployment         
metadata:                 
	name: nest-api
	namespace: default      
	labels:                 
		app: nest-api
spec:                    
	selector:               
		matchLables:          
			app: nest-api        
	replicas: 3             
	strategy:               
		rolingUpdate:         
			maxSurge: 1
			maxUnavilable: 0
		type: RolingUpdate
	template:             
		metadata:             
			labels:
				app: nest-api
		spec:                  
			containers:         
				- name: nest-api
				  image : ahmetkasap/nest-api:18
				  ports : 
					  - containerPort : 5000