apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
  namespace: default
  labels:
    app: nest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nest-api
    spec:
      containers:
        - name: nest-api
          image: ahmetkasap/nest-api:latest
          ports:
            - containerPort: 5000
