apiVersion: v1
kind: Deployment
metadata:
  name: nest-api
  namespace: default
  labels:
    app: nest-api
spec:
  selector:
    matchLabels:
      app: nest-api
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nest-api
    spec:
      containers:
        - name: nest-api
          image: ahmetkasap/nest-api:18
          ports:
            - containerPort: 5000