apiVersion: v1
kind: Service
metadata:
  name: nest-api-service
  namespace: default
  labels:          
    app: nest-api             
spec:
  type: LoadBalancer        
  selector:                 
    app: nest-api             
  ports:
    - protocol: TCP         
      port: 80              
      targetPort: 5000      
